"""add_koot_factors_and_kundali_matches

Revision ID: 18fe9913c8bf
Revises: 739b0127c7bd
Create Date: 2026-01-25 05:01:37.885554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18fe9913c8bf'
down_revision = '739b0127c7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kundali_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('boy_kundali_id', sa.UUID(), nullable=False),
    sa.Column('girl_kundali_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boy_kundali_id'], ['kundali_core.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['girl_kundali_id'], ['kundali_core.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kundali_matches_boy_kundali_id'), 'kundali_matches', ['boy_kundali_id'], unique=False)
    op.create_index(op.f('ix_kundali_matches_girl_kundali_id'), 'kundali_matches', ['girl_kundali_id'], unique=False)
    op.create_index(op.f('ix_kundali_matches_user_id'), 'kundali_matches', ['user_id'], unique=False)
    op.add_column('kundali_derived', sa.Column('koot_factors', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kundali_derived', 'koot_factors')
    op.drop_index(op.f('ix_kundali_matches_user_id'), table_name='kundali_matches')
    op.drop_index(op.f('ix_kundali_matches_girl_kundali_id'), table_name='kundali_matches')
    op.drop_index(op.f('ix_kundali_matches_boy_kundali_id'), table_name='kundali_matches')
    op.drop_table('kundali_matches')
    # ### end Alembic commands ###
