"""add_category_to_knowledge_item

Revision ID: 225cc653be46
Revises: 18fe9913c8bf
Create Date: 2026-01-26 00:23:56.908171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225cc653be46'
down_revision = '18fe9913c8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_items', sa.Column('category', sa.String(), nullable=True))
    op.add_column('knowledge_items', sa.Column('keywords', sa.String(), nullable=True))
    op.create_index(op.f('ix_knowledge_items_category'), 'knowledge_items', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_items_category'), table_name='knowledge_items')
    op.drop_column('knowledge_items', 'keywords')
    op.drop_column('knowledge_items', 'category')
    # ### end Alembic commands ###
