"""restore_metadata_info_column

Revision ID: 5f0e76a809d5
Revises: faf6bc5231c5
Create Date: 2026-01-18 23:16:20.103968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0e76a809d5'
down_revision = 'faf6bc5231c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_items', sa.Column('metadata_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_items', 'metadata_info')
    # ### end Alembic commands ###
