"""initial schema

Revision ID: bd39681e674b
Revises: 
Create Date: 2026-01-03 00:59:18.978776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd39681e674b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_key', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('effects', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key', 'version', name='uq_rule_key_version')
    )
    op.create_table('transits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transit_date', sa.Date(), nullable=False),
    sa.Column('planets', sa.JSON(), nullable=False),
    sa.Column('ayanamsa', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transit_date', 'ayanamsa', name='uq_transit_date_ayanamsa')
    )
    op.create_index(op.f('ix_transits_transit_date'), 'transits', ['transit_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('birth_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_time', sa.Time(), nullable=False),
    sa.Column('birth_place', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_birth_profiles_lat_lon', 'birth_profiles', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_birth_profiles_user_id'), 'birth_profiles', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_user_active', 'subscriptions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_logs_user_feature_time', 'usage_logs', ['user_id', 'feature', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    op.create_table('kundali_core',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('birth_profile_id', sa.UUID(), nullable=False),
    sa.Column('ascendant', sa.JSON(), nullable=False),
    sa.Column('planets', sa.JSON(), nullable=False),
    sa.Column('houses', sa.JSON(), nullable=False),
    sa.Column('ayanamsa', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['birth_profile_id'], ['birth_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('birth_profile_id', name='uq_kundali_core_birth_profile')
    )
    op.create_index(op.f('ix_kundali_core_birth_profile_id'), 'kundali_core', ['birth_profile_id'], unique=False)
    op.create_table('kundali_derived',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kundali_core_id', sa.UUID(), nullable=False),
    sa.Column('doshas', sa.JSON(), nullable=False),
    sa.Column('yogas', sa.JSON(), nullable=False),
    sa.Column('planet_strengths', sa.JSON(), nullable=False),
    sa.Column('house_strengths', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('calculation_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kundali_core_id'], ['kundali_core.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kundali_core_id', 'calculation_version', name='uq_kundali_derived_version')
    )
    op.create_index(op.f('ix_kundali_derived_kundali_core_id'), 'kundali_derived', ['kundali_core_id'], unique=False)
    op.create_table('kundali_divisional',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kundali_core_id', sa.UUID(), nullable=False),
    sa.Column('chart_type', sa.String(length=10), nullable=False),
    sa.Column('chart_data', sa.JSON(), nullable=False),
    sa.Column('calculation_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kundali_core_id'], ['kundali_core.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kundali_core_id', 'chart_type', 'calculation_version', name='uq_kundali_divisional_chart')
    )
    op.create_index(op.f('ix_kundali_divisional_kundali_core_id'), 'kundali_divisional', ['kundali_core_id'], unique=False)
    op.create_table('rule_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('kundali_core_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_key', sa.String(length=100), nullable=False),
    sa.Column('entity_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kundali_core_id'], ['kundali_core.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rule_mappings_entity', 'rule_mappings', ['entity_type', 'entity_key'], unique=False)
    op.create_index(op.f('ix_rule_mappings_kundali_core_id'), 'rule_mappings', ['kundali_core_id'], unique=False)
    op.create_index(op.f('ix_rule_mappings_rule_id'), 'rule_mappings', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_mappings_rule_id'), table_name='rule_mappings')
    op.drop_index(op.f('ix_rule_mappings_kundali_core_id'), table_name='rule_mappings')
    op.drop_index('ix_rule_mappings_entity', table_name='rule_mappings')
    op.drop_table('rule_mappings')
    op.drop_index(op.f('ix_kundali_divisional_kundali_core_id'), table_name='kundali_divisional')
    op.drop_table('kundali_divisional')
    op.drop_index(op.f('ix_kundali_derived_kundali_core_id'), table_name='kundali_derived')
    op.drop_table('kundali_derived')
    op.drop_index(op.f('ix_kundali_core_birth_profile_id'), table_name='kundali_core')
    op.drop_table('kundali_core')
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_index('ix_usage_logs_user_feature_time', table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_user_active', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_birth_profiles_user_id'), table_name='birth_profiles')
    op.drop_index('ix_birth_profiles_lat_lon', table_name='birth_profiles')
    op.drop_table('birth_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transits_transit_date'), table_name='transits')
    op.drop_table('transits')
    op.drop_table('rules')
    # ### end Alembic commands ###
