"""add_hnsw_index_to_knowledge_items

Revision ID: faf6bc5231c5
Revises: ea45fe123d7f
Create Date: 2026-01-18 22:56:42.957732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf6bc5231c5'
down_revision = 'ea45fe123d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_knowledge_items_embedding', 'knowledge_items', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_l2_ops'})
    op.drop_column('knowledge_items', 'metadata_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_items', sa.Column('metadata_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('ix_knowledge_items_embedding', table_name='knowledge_items', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_l2_ops'})
    # ### end Alembic commands ###
