from app.domain.kundali.schemas import KundaliChart
from app.domain.kundali.derived.schemas import DerivedAstrology

from app.domain.kundali.derived.house_calculator import HouseCalculator
from app.domain.kundali.derived.dosha_calculator import DoshaCalculator


class DerivedBuilder:
    """
    Builds derived astrology from a kundali chart
    by orchestrating multiple calculators.
    """

    def __init__(
        self,
        house_calculator: HouseCalculator | None = None,
        dosha_calculator: DoshaCalculator | None = None,
        calculation_version: str = "v1",
    ):
        self.house_calculator = house_calculator or HouseCalculator()
        self.dosha_calculator = dosha_calculator or DoshaCalculator()
        self.calculation_version = calculation_version

    def build(
        self,
        kundali: KundaliChart
    ) -> DerivedAstrology:
        """
        Build derived astrology for a given kundali chart.
        """

        # ─────────────────────────────────────────────
        # House strengths
        # ─────────────────────────────────────────────

        house_strengths = self.house_calculator.calculate(kundali)

        # ─────────────────────────────────────────────
        # Doshas
        # ─────────────────────────────────────────────

        doshas = self.dosha_calculator.calculate(kundali)

        # ─────────────────────────────────────────────
        # Assemble Derived Astrology
        # ─────────────────────────────────────────────

        return DerivedAstrology(
            doshas=doshas,
            yogas=[],  # populated later
            planet_strengths={},  # future expansion
            house_strengths=house_strengths,
            summary={},  # generated by rules / AI
            calculation_version=self.calculation_version,
        )
